-- Roles disponibles para AutoBrillo.
create table public.roles (
  "Id_Roles" integer generated by default as identity primary key,
  "Descripcion" varchar(100) not null unique
);

-- Datos iniciales que se mostrarán en el ABM.
insert into public.roles ("Descripcion") values
  ('Administrador'),
  ('Funcionarios'),
  ('Caja'),
  ('Stock'),
  ('Supervisor');

-- Cada usuario debe elegir exactamente un rol.
alter table public.usuarios add column "Id_Roles" integer;
update public.usuarios
set "Id_Roles" = (select "Id_Roles" from public.roles where "Descripcion" = 'Administrador')
where "Id_Roles" is null;
alter table public.usuarios alter column "Id_Roles" set not null;
alter table public.usuarios
  add constraint "FK_usuarios_roles_Id_Roles"
  foreign key ("Id_Roles") references public.roles ("Id_Roles") on delete restrict;

alter table public.roles enable row level security;
