-- Tabla inicial de AutoBrillo.
-- Password guarda exclusivamente el hash BCrypt generado por C#.
create table public.usuarios (
  "Id_Usuarios" integer generated by default as identity primary key,
  "Nombre" varchar(100) not null unique,
  "Password" varchar(255) not null
);

-- La API es la única que usa la conexión a la base de datos.
-- Se activa RLS para impedir el acceso directo desde clientes externos.
alter table public.usuarios enable row level security;
